import requests
import pandas as pd

# Definir os parâmetros da requisição
url_base = 'http://localhost:3000/query2'
data_inicio = '01.01.2007'
data_final = '01.10.2024'

empresas = [
    {'Simbolo': 'Airbus', 'Ramo': 'Aviacao'},
    {'Simbolo': 'Air Canada', 'Ramo': 'Aviacao'},
    {'Simbolo': 'Air China', 'Ramo': 'Aviacao'},
    {'Simbolo': 'Air France', 'Ramo': 'Aviacao'},
    {'Simbolo': 'Alaska Air Group', 'Ramo': 'Aviacao'},
    {'Simbolo': 'American Airlines', 'Ramo': 'Aviacao'},
    {'Simbolo': 'Azul', 'Ramo': 'Aviacao'},
    {'Simbolo': 'Boeing', 'Ramo': 'Aviacao'},
    {'Simbolo': 'Cargojet', 'Ramo': 'Aviacao'},
    {'Simbolo': 'China Airlines', 'Ramo': 'Aviacao'},
    {'Simbolo': 'Delta Air Lines', 'Ramo': 'Aviacao'},
    {'Simbolo': 'Embraer', 'Ramo': 'Aviacao'},
    {'Simbolo': 'Gol Linhas Aéreas', 'Ramo': 'Aviacao'},
    {'Simbolo': 'Japan Airlines', 'Ramo': 'Aviacao'},
    {'Simbolo': 'LATAM', 'Ramo': 'Aviacao'},
    {'Simbolo': 'Lockheed Martin', 'Ramo': 'Aviacao'},
    {'Simbolo': 'Lufthansa', 'Ramo': 'Aviacao'},
    {'Simbolo': 'Ryanair', 'Ramo': 'Aviacao'},
    {'Simbolo': 'Turkish Airlines', 'Ramo': 'Aviacao'},
    {'Simbolo': 'United Airlines', 'Ramo': 'Aviacao'},
    {'Simbolo': 'Chalco', 'Ramo': 'Commodities'},
    {'Simbolo': 'Archer Daniels Midland', 'Ramo': 'Commodities'},
    {'Simbolo': 'Bunge', 'Ramo': 'Commodities'},
    {'Simbolo': 'China Steel', 'Ramo': 'Commodities'},
    {'Simbolo': 'Glencore', 'Ramo': 'Commodities'},
    {'Simbolo': 'GrainCorp', 'Ramo': 'Commodities'},
    {'Simbolo': 'Mitsui', 'Ramo': 'Commodities'},
    {'Simbolo': 'Norsk Hydro', 'Ramo': 'Commodities'},
    {'Simbolo': 'Nucor', 'Ramo': 'Commodities'},
    {'Simbolo': 'Reliance Industries', 'Ramo': 'Commodities'},
    {'Simbolo': 'Sakata Seed', 'Ramo': 'Commodities'},
    {'Simbolo': 'Severstal', 'Ramo': 'Commodities'},
    {'Simbolo': 'Einhell Germany', 'Ramo': 'EquipamentosIndustriais'},
    {'Simbolo': 'Enerpac', 'Ramo': 'EquipamentosIndustriais'},
    {'Simbolo': 'Illinois Tool Works', 'Ramo': 'EquipamentosIndustriais'},
    {'Simbolo': 'Makita', 'Ramo': 'EquipamentosIndustriais'},
    {'Simbolo': 'Snap-On', 'Ramo': 'EquipamentosIndustriais'},
    {'Simbolo': 'Stanley Black & Decker', 'Ramo': 'EquipamentosIndustriais'},
    {'Simbolo': 'ToughBuilt', 'Ramo': 'EquipamentosIndustriais'},
    {'Simbolo': 'TOYA', 'Ramo': 'EquipamentosIndustriais'},
    {'Simbolo': 'Cacau', 'Ramo': 'Futures'},
    {'Simbolo': 'Café', 'Ramo': 'Futures'},
    {'Simbolo': 'Cobre', 'Ramo': 'Futures'},
    {'Simbolo': 'Algodão', 'Ramo': 'Futures'},
    {'Simbolo': 'Petróleo Bruto', 'Ramo': 'Futures'},
    {'Simbolo': 'Ouro', 'Ramo': 'Futures'},
    {'Simbolo': 'Óleo de aquecimento', 'Ramo': 'Futures'},
    {'Simbolo': 'Gado vivo', 'Ramo': 'Futures'},
    {'Simbolo': 'Gás natural', 'Ramo': 'Futures'},
    {'Simbolo': 'Paládio', 'Ramo': 'Futures'},
    {'Simbolo': 'Platina', 'Ramo': 'Futures'},
    {'Simbolo': 'Gasolina', 'Ramo': 'Futures'},
    {'Simbolo': 'Arroz', 'Ramo': 'Futures'},
    {'Simbolo': 'Prata', 'Ramo': 'Futures'},
    {'Simbolo': 'Soja', 'Ramo': 'Futures'},
    {'Simbolo': 'CAC 40', 'Ramo': 'Indices'},
    {'Simbolo': 'CBOE VIX', 'Ramo': 'Indices'},
    {'Simbolo': 'DAX', 'Ramo': 'Indices'},
    {'Simbolo': 'Dow Jones', 'Ramo': 'Indices'},
    {'Simbolo': 'FTSE 100', 'Ramo': 'Indices'},
    {'Simbolo': 'Hang Seng', 'Ramo': 'Indices'},
    {'Simbolo': 'Bovespa', 'Ramo': 'Indices'},
    {'Simbolo': 'NASDAQ', 'Ramo': 'Indices'},
    {'Simbolo': 'Nikkei', 'Ramo': 'Indices'},
    {'Simbolo': 'Russell 2000', 'Ramo': 'Indices'},
    {'Simbolo': 'S&P 500', 'Ramo': 'Indices'},
    {'Simbolo': 'Aston Martin', 'Ramo': 'IndustriaAutomotiva'},
    {'Simbolo': 'BMW', 'Ramo': 'IndustriaAutomotiva'},
    {'Simbolo': 'Porsche', 'Ramo': 'IndustriaAutomotiva'},
    {'Simbolo': 'Ferrari', 'Ramo': 'IndustriaAutomotiva'},
    {'Simbolo': 'Ford', 'Ramo': 'IndustriaAutomotiva'},
    {'Simbolo': 'General Motors', 'Ramo': 'IndustriaAutomotiva'},
    {'Simbolo': 'Honda', 'Ramo': 'IndustriaAutomotiva'},
    {'Simbolo': 'Hyundai', 'Ramo': 'IndustriaAutomotiva'},
    {'Simbolo': 'IVECO', 'Ramo': 'IndustriaAutomotiva'},
    {'Simbolo': 'Mercedes-Benz', 'Ramo': 'IndustriaAutomotiva'},
    {'Simbolo': 'Mitsubishi Motors', 'Ramo': 'IndustriaAutomotiva'},
    {'Simbolo': 'Nissan', 'Ramo': 'IndustriaAutomotiva'},
    {'Simbolo': 'Rheinmetall', 'Ramo': 'IndustriaAutomotiva'},
    {'Simbolo': 'Stellantis', 'Ramo': 'IndustriaAutomotiva'},
    {'Simbolo': 'Tesla', 'Ramo': 'IndustriaAutomotiva'},
    {'Simbolo': 'Toyota', 'Ramo': 'IndustriaAutomotiva'},
    {'Simbolo': 'Volkswagen', 'Ramo': 'IndustriaAutomotiva'},
    {'Simbolo': 'Alexandria REIT', 'Ramo': 'MercadoImobiliario'},
    {'Simbolo': 'American Tower', 'Ramo': 'MercadoImobiliario'},
    {'Simbolo': 'AvalonBay', 'Ramo': 'MercadoImobiliario'},
    {'Simbolo': 'CBRE', 'Ramo': 'MercadoImobiliario'},
    {'Simbolo': 'CoStar', 'Ramo': 'MercadoImobiliario'},
    {'Simbolo': 'Crown Castle', 'Ramo': 'MercadoImobiliario'},
    {'Simbolo': 'Digital Realty', 'Ramo': 'MercadoImobiliario'},
    {'Simbolo': 'DLF', 'Ramo': 'MercadoImobiliario'},
    {'Simbolo': 'Equity Residential', 'Ramo': 'MercadoImobiliario'},
    {'Simbolo': 'Kennedy-Wilson', 'Ramo': 'MercadoImobiliario'},
    {'Simbolo': 'Mitsubishi Estate', 'Ramo': 'MercadoImobiliario'},
    {'Simbolo': 'Mitsui Fudosan', 'Ramo': 'MercadoImobiliario'},
    {'Simbolo': 'Prologis', 'Ramo': 'MercadoImobiliario'},
    {'Simbolo': 'Public Storage', 'Ramo': 'MercadoImobiliario'},
    {'Simbolo': 'Realty Income', 'Ramo': 'MercadoImobiliario'},
    {'Simbolo': 'Simon Property', 'Ramo': 'MercadoImobiliario'},
    {'Simbolo': 'VICI Properties', 'Ramo': 'MercadoImobiliario'},
    {'Simbolo': 'Welltower', 'Ramo': 'MercadoImobiliario'},
    {'Simbolo': 'AMC', 'Ramo': 'MidiaEntretenimento'},
    {'Simbolo': 'AT&T', 'Ramo': 'MidiaEntretenimento'},
    {'Simbolo': 'Charter Communications', 'Ramo': 'MidiaEntretenimento'},
    {'Simbolo': 'Comcast', 'Ramo': 'MidiaEntretenimento'},
    {'Simbolo': 'Fox', 'Ramo': 'MidiaEntretenimento'},
    {'Simbolo': 'Fuji Media', 'Ramo': 'MidiaEntretenimento'},
    {'Simbolo': 'Liberty Media', 'Ramo': 'MidiaEntretenimento'},
    {'Simbolo': 'Meta', 'Ramo': 'MidiaEntretenimento'},
    {'Simbolo': 'Netflix', 'Ramo': 'MidiaEntretenimento'},
    {'Simbolo': 'Nippon Television', 'Ramo': 'MidiaEntretenimento'},
    {'Simbolo': 'Omnicom', 'Ramo': 'MidiaEntretenimento'},
    {'Simbolo': 'Paramount', 'Ramo': 'MidiaEntretenimento'},
    {'Simbolo': 'Sony', 'Ramo': 'MidiaEntretenimento'},
    {'Simbolo': 'Spotify', 'Ramo': 'MidiaEntretenimento'},
    {'Simbolo': 'Toppan', 'Ramo': 'MidiaEntretenimento'},
    {'Simbolo': 'Vivendi', 'Ramo': 'MidiaEntretenimento'},
    {'Simbolo': 'Disney', 'Ramo': 'MidiaEntretenimento'},
    {'Simbolo': 'Warner Bros', 'Ramo': 'MidiaEntretenimento'},
    {'Simbolo': 'Adidas', 'Ramo': 'Moda'},
    {'Simbolo': 'Burberry', 'Ramo': 'Moda'},
    {'Simbolo': 'Christian Dior', 'Ramo': 'Moda'},
    {'Simbolo': 'Fila', 'Ramo': 'Moda'},
    {'Simbolo': 'HNM', 'Ramo': 'Moda'},
    {'Simbolo': 'Hermès', 'Ramo': 'Moda'},
    {'Simbolo': 'Inditex', 'Ramo': 'Moda'},
    {'Simbolo': "Levi's", 'Ramo': 'Moda'},
    {'Simbolo': 'Lojas Renner', 'Ramo': 'Moda'},
    {'Simbolo': 'LVMH', 'Ramo': 'Moda'},
    {'Simbolo': 'Moncler', 'Ramo': 'Moda'},
    {'Simbolo': 'Nike', 'Ramo': 'Moda'},
    {'Simbolo': 'Puma', 'Ramo': 'Moda'},
    {'Simbolo': 'Ralph Lauren', 'Ramo': 'Moda'},
    {'Simbolo': 'TJX', 'Ramo': 'Moda'},
    {'Simbolo': 'Under Armour', 'Ramo': 'Moda'},
    {'Simbolo': "Victoria's Secret", 'Ramo': 'Moda'},
    {'Simbolo': 'Baker Hughes', 'Ramo': 'Petroleo'},
    {'Simbolo': 'BP', 'Ramo': 'Petroleo'},
    {'Simbolo': 'Chandra Asri', 'Ramo': 'Petroleo'},
    {'Simbolo': 'Chevron', 'Ramo': 'Petroleo'},
    {'Simbolo': 'CNOOC', 'Ramo': 'Petroleo'},
    {'Simbolo': 'ENI', 'Ramo': 'Petroleo'},
    {'Simbolo': 'Equinor', 'Ramo': 'Petroleo'},
    {'Simbolo': 'ExxonMobil', 'Ramo': 'Petroleo'},
    {'Simbolo': 'Gazprom', 'Ramo': 'Petroleo'},
    {'Simbolo': 'Imperial Oil', 'Ramo': 'Petroleo'},
    {'Simbolo': 'Lukoil', 'Ramo': 'Petroleo'},
    {'Simbolo': 'PetroChina', 'Ramo': 'Petroleo'},
    {'Simbolo': 'Petrobras', 'Ramo': 'Petroleo'},
    {'Simbolo': 'Phillips 66', 'Ramo': 'Petroleo'},
    {'Simbolo': 'Rosneft', 'Ramo': 'Petroleo'},
    {'Simbolo': 'Saudi Aramco', 'Ramo': 'Petroleo'},
    {'Simbolo': 'Shell', 'Ramo': 'Petroleo'},
    {'Simbolo': 'Sinopec', 'Ramo': 'Petroleo'},
    {'Simbolo': 'AstraZeneca', 'Ramo': 'Saude'},
    {'Simbolo': 'Bayer', 'Ramo': 'Saude'},
    {'Simbolo': 'Cardinal Health', 'Ramo': 'Saude'},
    {'Simbolo': 'Cencora', 'Ramo': 'Saude'},
    {'Simbolo': 'Centene', 'Ramo': 'Saude'},
    {'Simbolo': 'CVS Health', 'Ramo': 'Saude'},
    {'Simbolo': 'Daewoong Pharmaceutical', 'Ramo': 'Saude'},
    {'Simbolo': 'DHG Pharma', 'Ramo': 'Saude'},
    {'Simbolo': 'Elevance Health', 'Ramo': 'Saude'},
    {'Simbolo': 'Eli Lilly', 'Ramo': 'Saude'},
    {'Simbolo': 'Humana', 'Ramo': 'Saude'},
    {'Simbolo': 'Johnson & Johnson', 'Ramo': 'Saude'},
    {'Simbolo': 'McKesson', 'Ramo': 'Saude'},
    {'Simbolo': 'Novartis', 'Ramo': 'Saude'},
    {'Simbolo': 'Pfizer', 'Ramo': 'Saude'},
    {'Simbolo': 'Samsung Biologics', 'Ramo': 'Saude'},
    {'Simbolo': 'Sanofi', 'Ramo': 'Saude'},
    {'Simbolo': 'Cigna', 'Ramo': 'Saude'},
    {'Simbolo': 'UnitedHealth', 'Ramo': 'Saude'},
    {'Simbolo': 'Walgreens Boots', 'Ramo': 'Saude'},
    {'Simbolo': 'American Express', 'Ramo': 'ServicosFinanceiros'},
    {'Simbolo': 'Santander', 'Ramo': 'ServicosFinanceiros'},
    {'Simbolo': 'Banco do Brasil', 'Ramo': 'ServicosFinanceiros'},
    {'Simbolo': 'Bank of America', 'Ramo': 'ServicosFinanceiros'},
    {'Simbolo': 'Bank of China', 'Ramo': 'ServicosFinanceiros'},
    {'Simbolo': 'BNP Paribas', 'Ramo': 'ServicosFinanceiros'},
    {'Simbolo': 'Citigroup', 'Ramo': 'ServicosFinanceiros'},
    {'Simbolo': 'Commonwealth Bank', 'Ramo': 'ServicosFinanceiros'},
    {'Simbolo': 'Emirates NBD', 'Ramo': 'ServicosFinanceiros'},
    {'Simbolo': 'Goldman Sachs', 'Ramo': 'ServicosFinanceiros'},
    {'Simbolo': 'HSBC', 'Ramo': 'ServicosFinanceiros'},
    {'Simbolo': 'ICBC', 'Ramo': 'ServicosFinanceiros'},
    {'Simbolo': 'Itaú', 'Ramo': 'ServicosFinanceiros'},
    {'Simbolo': 'JPMorgan Chase', 'Ramo': 'ServicosFinanceiros'},
    {'Simbolo': 'Mastercard', 'Ramo': 'ServicosFinanceiros'},
    {'Simbolo': 'Morgan Stanley', 'Ramo': 'ServicosFinanceiros'},
    {'Simbolo': 'PayPal', 'Ramo': 'ServicosFinanceiros'},
    {'Simbolo': 'Royal Bank of Canada', 'Ramo': 'ServicosFinanceiros'},
    {'Simbolo': 'Visa', 'Ramo': 'ServicosFinanceiros'},
    {'Simbolo': 'Adobe', 'Ramo': 'Tecnologia'},
    {'Simbolo': 'AMD', 'Ramo': 'Tecnologia'},
    {'Simbolo': 'Google (Alphabet)', 'Ramo': 'Tecnologia'},
    {'Simbolo': 'Amazon', 'Ramo': 'Tecnologia'},
    {'Simbolo': 'Apple', 'Ramo': 'Tecnologia'},
    {'Simbolo': 'Cisco', 'Ramo': 'Tecnologia'},
    {'Simbolo': 'CrowdStrike', 'Ramo': 'Tecnologia'},
    {'Simbolo': 'Dell', 'Ramo': 'Tecnologia'},
    {'Simbolo': 'Intel', 'Ramo': 'Tecnologia'},
    {'Simbolo': 'IBM', 'Ramo': 'Tecnologia'},
    {'Simbolo': 'Microsoft', 'Ramo': 'Tecnologia'},
    {'Simbolo': 'NVIDIA', 'Ramo': 'Tecnologia'},
    {'Simbolo': 'Oracle', 'Ramo': 'Tecnologia'},
    {'Simbolo': 'Qualcomm', 'Ramo': 'Tecnologia'},
    {'Simbolo': 'Samsung', 'Ramo': 'Tecnologia'},
    {'Simbolo': 'TSMC', 'Ramo': 'Tecnologia'},
    {'Simbolo': 'Tencent', 'Ramo': 'Tecnologia'},
    {'Simbolo': 'Verizon', 'Ramo': 'Tecnologia'},
    {'Simbolo': 'Xiaomi', 'Ramo': 'Tecnologia'},
    {'Simbolo': 'Canadian National Railway', 'Ramo': 'TransporteLogistica'},
    {'Simbolo': 'China Railway Construction', 'Ramo': 'TransporteLogistica'},
    {'Simbolo': 'COSCO Shipping', 'Ramo': 'TransporteLogistica'},
    {'Simbolo': 'CSX', 'Ramo': 'TransporteLogistica'},
    {'Simbolo': 'Evergreen Marine', 'Ramo': 'TransporteLogistica'},
    {'Simbolo': 'FedEx', 'Ramo': 'TransporteLogistica'},
    {'Simbolo': 'HMM', 'Ramo': 'TransporteLogistica'},
    {'Simbolo': 'Indian Railway Finance', 'Ramo': 'TransporteLogistica'},
    {'Simbolo': 'InPost', 'Ramo': 'TransporteLogistica'},
    {'Simbolo': 'NYK Line', 'Ramo': 'TransporteLogistica'},
    {'Simbolo': 'Old Dominion Freight', 'Ramo': 'TransporteLogistica'},
    {'Simbolo': 'Orient Overseas (OOIL)', 'Ramo': 'TransporteLogistica'},
    {'Simbolo': 'Qatar Gas Transport', 'Ramo': 'TransporteLogistica'},
    {'Simbolo': 'Uber', 'Ramo': 'TransporteLogistica'},
    {'Simbolo': 'Union Pacific', 'Ramo': 'TransporteLogistica'},
    {'Simbolo': 'UPS', 'Ramo': 'TransporteLogistica'}
]

# Extrair todos os ramos únicos
ramos = set(empresa['Ramo'] for empresa in empresas)

# Criar um DataFrame vazio para armazenar todos os dados
dados_totais = pd.DataFrame()

# Iterar sobre cada ramo e fazer a requisição correspondente com todos os símbolos desse ramo
for ramo in ramos:
    # Filtrar símbolos do ramo atual
    simbolos_ramo = [empresa['Simbolo'] for empresa in empresas if empresa['Ramo'] == ramo]
    simbolos_str = ','.join(simbolos_ramo)
    
    params = {
        'ramo': ramo,
        'simbolos': simbolos_str,
        'data_inicio': data_inicio,
        'data_final': data_final
    }

    response = requests.get(url_base, params=params)

    if response.status_code == 200:
        dados = response.json()
        df = pd.DataFrame(dados)

        # Converter campos de texto para os tipos apropriados
        df['Data'] = pd.to_datetime(df['Data'], format='%d.%m.%Y')
        df['Fechamento'] = pd.to_numeric(df['Fechamento'], errors='coerce')
        df['Fechamento_Padronizado'] = pd.to_numeric(df['Fechamento_Padronizado'], errors='coerce')

        # Adicionar ao DataFrame total
        dados_totais = pd.concat([dados_totais, df], ignore_index=True)
    else:
        print(f"Erro na requisição para ramo {ramo} - Status Code: {response.status_code}")

# Salvar todos os dados em um único arquivo Excel
dados_totais.to_excel('dados.xlsx', index=False)
print("Dados salvos em dados.xlsx")
